#!/bin/bash
set -euo pipefail

# Generated by android-adb-explorer-gen
# Run ID: <RUN_ID>
# Goal: <自然语言目标描述>
# Evidence root: evidence/android-explorer-<RUN_ID>/
# NOTE: Fixed coordinates from exploration. Re-run if UI changes significantly.

PKG="<APP_PACKAGE>"

adb_cmd() { adb ${ANDROID_SERIAL:+-s "$ANDROID_SERIAL"} "$@"; }

# 轮询当前 Focus Activity，$1=关键字(正则) $2=超时秒
# 兼容要点(勿改)：
#   1) adb 输出为 CRLF，必须 tr -d '\r'
#   2) macOS BSD grep 中字符类 [^\n] 会被解释为"非字母 n"，行内匹配用 . 代替
#   3) set -o pipefail 下 grep -q 提前退出会让上游 tr 收 SIGPIPE 导致管道判失败，
#      必须先命令替换赋值，再用 here-string 喂 grep
wait_activity() {
  local frag="$1" ttl="$2" n=0 focus
  while (( n < ttl )); do
    focus=$(adb_cmd shell dumpsys window 2>/dev/null | tr -d '\r' || true)
    if grep -aqE "mCurrentFocus.*$frag" <<< "$focus"; then
      echo "  [ok] activity matched: $frag"; return 0
    fi
    sleep 1; n=$((n+1))
  done
  echo "  [WARN] wait activity '$frag' timeout after ${ttl}s" >&2
}

# ---- step-01 launch (evidence: step-01_launch_app/) ----
echo "[1/N] 启动 $PKG"
adb_cmd shell cmd statusbar collapse >/dev/null 2>&1 || true
adb_cmd shell am force-stop "$PKG"
adb_cmd shell monkey -p "$PKG" -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1
wait_activity "<LAUNCH_ACTIVITY_FRAGMENT>" 12
sleep 2   # 等首页内容渲染

# ---- step-02 tap (evidence: step-02_*/) ----
# 目标: <desc>；定位依据: <rid/text/cd + 是否祖先代理>；中心(<CX>,<CY>)
echo "[2/N] <操作说明> -> tap <CX> <CY>"
adb_cmd shell input tap "<CX>" "<CY>"
sleep 2

# ---- 更多 tap/swipe 步骤 ... ----
# swipe 找元素时: duration >= 800ms (1px/ms 慢速无惯性)，幅度 <= 有效视口高度
# adb_cmd shell input swipe 540 1800 540 800 1000

# ---- assertion (纯 adb) ----
FOCUS=$(adb_cmd shell dumpsys window 2>/dev/null | tr -d '\r' | grep -a "mCurrentFocus" | head -1)
echo "当前 Focus: $FOCUS"
if echo "$FOCUS" | grep -q "<EXPECTED_ACTIVITY_FRAGMENT>"; then
  echo "[SUCCESS] 已到达目标页面。视觉确认: adb exec-out screencap -p > result.png"
  # 可选 CDP 终态验证(debug 包，H5 页面):
  #   PID=$(adb shell pidof "$PKG" | tr -d '\r')
  #   adb forward tcp:9222 localabstract:webview_devtools_remote_$PID
  #   curl -s http://127.0.0.1:9222/json | grep -E '<页面标题或URL特征>'
  exit 0
else
  echo "[FAILED] 未到达目标页面，对照证据 step-*/after/ 排查" >&2
  exit 1
fi
